users_list:
  - name: devops
    shell: /bin/bash
    groups: wheel
    ssh_key: "{{ ssh_public_key }}"
    sudo: true
  - name: auditor
    shell: /bin/bash
    ssh_key: "{{ ssh_public_key }}"
    sudo: false
